// Generated by CoffeeScript 1.7.1
(function() {
  var async, backbone;

  async = require('async');

  backbone = function(req, res, callback) {
    var $ctrl, action, middlewares;
    $ctrl = req.$ctrl, action = req.action, middlewares = req.middlewares;
    return async.waterfall([
      function(next) {
        return async.eachSeries(middlewares, function(fn, next) {
          return fn(req, res, next);
        }, next);
      }, function(next) {
        if ($ctrl[action].length === 3) {
          return $ctrl[action](req, res, next);
        } else {
          return $ctrl[action](req, next);
        }
      }
    ], function(err, result) {
      res.set('err', err);
      res.set('result', result);
      return callback(req, res);
    });
  };

  module.exports = backbone;

}).call(this);
