// Generated by CoffeeScript 1.7.1
(function() {
  var commander, program, shelljs;

  commander = require('commander');

  shelljs = require('shelljs');

  program = commander.command('init');

  commander.parse(process.argv);

}).call(this);
