// Generated by CoffeeScript 1.7.1
(function() {
  var router;

  router = require('./router');

  module.exports = {
    routes: function(app, fn) {
      return typeof fn === "function" ? fn(router(app)) : void 0;
    },
    express: function(app, fn) {
      return typeof fn === "function" ? fn(app) : void 0;
    }
  };

}).call(this);
