// Generated by CoffeeScript 1.7.1
(function() {
  var Request, Response, router;

  router = require('./router');

  Request = require('./request');

  Response = require('./response');

  module.exports = {
    routes: function(app, fn) {
      return typeof fn === "function" ? fn(router(app)) : void 0;
    },
    express: function(app, fn) {
      return typeof fn === "function" ? fn(app) : void 0;
    },
    request: function(app, fn) {
      return typeof fn === "function" ? fn(Request) : void 0;
    },
    response: function(app, fn) {
      return typeof fn === "function" ? fn(Response) : void 0;
    }
  };

}).call(this);
