// Generated by CoffeeScript 1.7.1
(function() {
  var BaseController, afterAction, beforeAction, ensure, select, util, _, _insertCallbacks, _mix, _mixin, _normalizeOptions,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    __slice = [].slice;

  _ = require('lodash');

  util = require('./util');

  ensure = require('./decorators/ensure');

  beforeAction = require('./decorators/before');

  afterAction = require('./decorators/after');

  select = require('./decorators/select');

  _mix = function(base, target) {
    var ignores, key, prop;
    ignores = ['__super__', 'constructor'];
    for (key in target) {
      prop = target[key];
      if (hasOwnProperty.call(target, key) && __indexOf.call(ignores, key) < 0) {
        base[key] = prop;
      }
    }
    return base;
  };

  _mixin = function(child, parent) {
    if (toString.call(parent) === '[object Array]') {
      parent.forEach(function(obj) {
        return _mixin(child, obj);
      });
    } else {
      _mix(child, parent);
      _mix(child.prototype, parent.prototype);
    }
    return child;
  };

  _normalizeOptions = function(options) {
    var except, only;
    only = options.only, except = options.except;
    options.only = util._toArray(only);
    options.except = util._toArray(except);
    options.parallel || (options.parallel = false);
    return options;
  };

  _insertCallbacks = function(fn, props) {
    var except, only, options, parallel, _applyCallback, _fn, _ref;
    if (props == null) {
      props = [];
    }
    if (toString.call(props) === '[object Arguments]') {
      props = Array.prototype.slice.call(props, 0);
    }
    if (!this._beforeActions) {
      this._beforeActions = [];
    }
    if (!this._afterActions) {
      this._afterActions = [];
    }
    options = toString.call(props[props.length - 1]) === '[object Object]' ? props.pop() : {};
    _ref = _normalizeOptions(options), only = _ref.only, except = _ref.except, parallel = _ref.parallel;
    _fn = fn.apply(this, props);
    _applyCallback = function() {
      var action, args, next, req, res;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      req = args[0], res = args[1];
      next = args.pop();
      action = req.action;
      if ((!_.isEmpty(only) && __indexOf.call(only, action) < 0) || (!_.isEmpty(except) && __indexOf.call(except, action) >= 0)) {
        return next(null, args[2] || {});
      } else {
        if (parallel) {
          _fn.apply(this, args);
          return next(null, args[2] || {});
        } else {
          return _fn.apply(this, arguments);
        }
      }
    };
    if (fn.before) {
      this._beforeActions.push(_applyCallback);
    }
    if (fn.after) {
      return this._afterActions.push(_applyCallback);
    }
  };

  BaseController = (function() {
    function BaseController() {}

    BaseController.mixin = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return _mixin(this, args);
    };

    BaseController.ensure = function() {
      return _insertCallbacks.call(this, ensure, arguments);
    };

    BaseController.before = function() {
      return _insertCallbacks.call(this, beforeAction, arguments);
    };

    BaseController.after = function() {
      return _insertCallbacks.call(this, afterAction, arguments);
    };

    BaseController.select = function() {
      return _insertCallbacks.call(this, select, arguments);
    };

    return BaseController;

  })();

  module.exports = BaseController;

}).call(this);
