// Generated by CoffeeScript 1.7.1
(function() {
  var BaseHelper;

  BaseHelper = (function() {
    function BaseHelper() {}

    return BaseHelper;

  })();

  module.exports = BaseHelper;

}).call(this);
