// Generated by CoffeeScript 1.7.1
(function() {
  var BaseMailer;

  BaseMailer = (function() {
    function BaseMailer() {}

    return BaseMailer;

  })();

  module.exports = BaseMailer;

}).call(this);
