// Generated by CoffeeScript 1.7.1
(function() {
  var response, _configer;

  _configer = function() {};

  response = function(req, res, next) {
    _configer.call(res, res);
    return next();
  };

  response.configer = function(app, fn) {
    if (fn == null) {
      fn = function() {};
    }
    _configer = fn;
    return app.use(response);
  };

  module.exports = response;

}).call(this);
