// Generated by CoffeeScript 1.7.1
(function() {
  var response, _config;

  _config = function() {};

  response = function(req, res, next) {
    res.response = function(err, result) {
      if (err != null) {
        return res.status((typeof err.toStatus === "function" ? err.toStatus() : void 0) || 400).json((typeof err.toJSON === "function" ? err.toJSON() : void 0) || {
          message: err.message
        });
      } else {
        return res.status(200).json(result);
      }
    };
    _config.call(res, res);
    return next();
  };

  response.config = function(app, fn) {
    if (fn == null) {
      fn = function() {};
    }
    _config = fn;
    return app.use(response);
  };

  module.exports = response;

}).call(this);
