// Generated by CoffeeScript 1.7.1
(function() {
  var response;

  response = require('express').response;

  response.config = function(app, fn) {
    if (fn == null) {
      fn = function() {};
    }
    response.response = function() {
      var err, result;
      err = this.err, result = this.result;
      if (err != null) {
        return this.status(err.status || 400).json((typeof err.toJSON === "function" ? err.toJSON() : void 0) || {
          message: err.message
        });
      } else {
        return this.status(200).json(result);
      }
    };
    return fn.call(response, response);
  };

  module.exports = response;

}).call(this);
