// Generated by CoffeeScript 1.7.1
(function() {
  var Router, async, backbone, inflection, p, router, _;

  _ = require('lodash');

  async = require('async');

  inflection = require('inflection');

  backbone = require('./backbone');

  p = require('path');

  Router = (function() {
    var _parseDsl;

    function Router(app) {
      this.app = app;
    }

    Router.prototype.middlewares = [];

    Router.prototype.prefix = null;

    Router.prototype._resource = function(ctrl) {
      ctrl = inflection.pluralize(ctrl);
      return {
        readOne: {
          method: 'get',
          path: "/" + ctrl + "/:_id"
        },
        read: {
          method: 'get',
          path: "/" + ctrl
        },
        create: {
          method: 'post',
          path: "/" + ctrl
        },
        update: {
          method: 'put',
          path: "/" + ctrl + "/:_id"
        },
        remove: {
          method: 'delete',
          path: "/" + ctrl + "/:_id"
        }
      };
    };

    _parseDsl = function(path, options) {
      var action, ctrl, to, _ref;
      if (options == null) {
        options = {};
      }
      if (arguments.length === 2) {
        options.path = path;
        to = options.to;
        if (to != null) {
          _ref = to.split('#'), ctrl = _ref[0], action = _ref[1];
          action || (action = 'index');
          options.ctrl || (options.ctrl = ctrl);
          options.action || (options.action = action);
        }
      } else {
        options = path;
      }
      return options;
    };

    Router.prototype.callback = function(req, res) {
      return res.response();
    };

    Router.prototype.resource = function(ctrl, options) {
      var action, except, map, only, opt, _options, _results;
      if (options == null) {
        options = {};
      }
      map = this._resource(ctrl);
      only = options.only, except = options.except;
      if (only != null) {
        map = _.pick(map, only);
      } else if (except != null) {
        map = _.omit(map, except);
      }
      _results = [];
      for (action in map) {
        opt = map[action];
        _options = _.extend(options, {
          ctrl: ctrl,
          action: action,
          method: opt.method,
          path: opt.path
        });
        _results.push(this._apply(_options));
      }
      return _results;
    };

    Router.prototype.get = function() {
      var options;
      options = _parseDsl.apply(this, arguments);
      options.method = 'get';
      return this._apply(options);
    };

    Router.prototype.post = function() {
      var options;
      options = _parseDsl.apply(this, arguments);
      options.method = 'post';
      return this._apply(options);
    };

    Router.prototype.put = function() {
      var options;
      options = _parseDsl.apply(this, arguments);
      options.method = 'put';
      return this._apply(options);
    };

    Router.prototype["delete"] = function() {
      var options;
      options = _parseDsl.apply(this, arguments);
      options.method = 'delete';
      return this._apply(options);
    };

    Router.prototype.options = function() {
      var options;
      options = _parseDsl.apply(this, arguments);
      options.method = 'options';
      return this._apply(options);
    };

    Router.prototype._apply = function(options) {
      var action, callback, ctrl, method, middlewares, path, sundae, _ctrl;
      if (options == null) {
        options = {};
      }
      ctrl = options.ctrl, action = options.action, method = options.method, path = options.path, middlewares = options.middlewares, callback = options.callback;
      middlewares || (middlewares = this.middlewares);
      callback || (callback = this.callback);
      action || (action = 'index');
      sundae = require('./sundae');
      _ctrl = require(p.join(sundae.get('mainPath'), "controllers/" + ctrl));
      if (typeof _ctrl[action] !== 'function') {
        return false;
      }
      if (toString.call(path) === '[object String]' && this.prefix) {
        path = '/' + p.join(this.prefix, path);
      }
      return this.app[method](path, function(req, res, next) {
        req._ctrl = _ctrl;
        req.ctrl = ctrl;
        req.action = action;
        req.middlewares = middlewares;
        return backbone(req, res, callback);
      });
    };

    Router.prototype.http404 = function(req, res, next) {
      return res.status(404).json({
        message: 'Not Found'
      });
    };

    Router.prototype.http500 = function(err, req, res, next) {
      return res.status(500).json({
        error: (err != null ? err.message : void 0) || 'Internal Server Error'
      });
    };

    return Router;

  })();

  router = function(app) {
    return new Router(app);
  };

  router.config = function(app, fn) {
    var _router;
    _router = router(app);
    if (typeof fn === "function") {
      fn(_router);
    }
    app.use(_router.http404);
    return app.use(_router.http500);
  };

  router.key = 'routes';

  module.exports = router;

}).call(this);
