// Generated by CoffeeScript 1.6.3
(function() {
  var Sundae, express, http, socketIo, sundae, _;

  _ = require('lodash');

  http = require('http');

  express = require('express');

  socketIo = require('socket.io');

  Sundae = (function() {
    function Sundae() {}

    Sundae.prototype.init = function(options) {
      if (options == null) {
        options = {};
      }
      this.options = _.extend({
        port: 3011
      }, options);
      return this;
    };

    Sundae.prototype.run = function(callback) {
      var app, io, server;
      if (callback == null) {
        callback = function() {};
      }
      app = this.app = express();
      server = this.server = http.createServer(app);
      io = this.io = socketIo.listen(server);
      return server.listen(this.options.port, callback);
    };

    Sundae.prototype.reload = function(callback) {
      if (callback == null) {
        callback = function() {};
      }
    };

    return Sundae;

  })();

  sundae = new Sundae;

  sundae.Sundae = Sundae;

  module.exports = sundae;

}).call(this);
