// Generated by CoffeeScript 1.7.1
(function() {
  var util;

  util = module.exports;

  util._toArray = function(obj) {
    if (toString.call(obj) === '[object String]') {
      obj = obj.split(new RegExp(' +'));
    }
    if (toString.call(obj) === '[object Array]') {
      return obj;
    } else {
      return [];
    }
  };

}).call(this);
