// Generated by CoffeeScript 1.6.3
(function() {
  var $errorHandler, CustomError, ErrorHandler, errorHandler, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ = require('lodash');

  CustomError = (function(_super) {
    __extends(CustomError, _super);

    function CustomError(msg, code) {
      this.msg = msg != null ? msg : '';
      this.code = code != null ? code : null;
      CustomError.__super__.constructor.apply(this, arguments);
    }

    CustomError.prototype.toJSON = function() {
      return {
        code: this.toCode(),
        msg: this.toMsg()
      };
    };

    CustomError.prototype.toCode = function() {
      return Number(this.code.toString().slice(3));
    };

    CustomError.prototype.toStatus = function() {
      return Number(this.code.toString().slice(0, 3));
    };

    CustomError.prototype.toMsg = function() {
      return this.msg;
    };

    return CustomError;

  })(Error);

  ErrorHandler = (function() {
    function ErrorHandler() {
      this._codes = {
        error: 502900
      };
      this._msgs = {
        error: 'Unknown Error',
        succ: 'Success'
      };
      Object.defineProperties(this, {
        'codes': {
          get: function() {
            return this._codes;
          },
          set: function(_codes) {
            return this._codes = _.extend(this._codes, _codes);
          }
        },
        'msgs': {
          get: function() {
            return this._msgs;
          },
          set: function(_msgs) {
            return this._msgs = _.extend(this._msgs, _msgs);
          }
        }
      });
    }

    ErrorHandler.prototype.register = function(errors) {
      if (typeof errors === 'function') {
        return errors.call(this);
      }
    };

    ErrorHandler.prototype.parse = function(err) {
      var $err, args, code, flag, msg;
      if (typeof err === 'string' && (this.msgs[err] != null)) {
        return $err = new CustomError(this.msgs[err], this.codes[err]);
      } else if (err instanceof Array) {
        flag = err[0], args = err[1];
        if (typeof this.msgs[flag] === 'function') {
          msg = this.msgs[flag].apply(this, args);
        } else if (this.msgs[flag] != null) {
          msg = this.msgs[flag];
        } else {
          msg = this.msgs.error;
        }
        code = this.codes[flag] || this.codes.error;
        return new CustomError(msg, code);
      } else {
        return new CustomError(err, this.codes.error);
      }
    };

    return ErrorHandler;

  })();

  $errorHandler = new ErrorHandler;

  errorHandler = function(errors) {
    if ('function' ? typeof errors : void 0) {
      $errorHandler.register(errors);
    }
    return $errorHandler;
  };

  module.exports = errorHandler;

}).call(this);
