// Generated by CoffeeScript 1.6.3
(function() {
  var Router, bundle, error, logger, path, router,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  path = require('path');

  logger = require('graceful-logger');

  bundle = require('./bundle');

  error = require('./error')();

  Router = (function() {
    var _baseDir, _resTypes;

    _baseDir = process.cwd();

    _resTypes = ['json', 'html'];

    function Router(sundae) {
      var _this = this;
      this.sundae = sundae;
      this.application = 'json';
      this.appRoot = "" + (sundae.get('root') || _baseDir) + "/app";
      this.app = this.sundae.app;
      this.rests = [];
      this.callback = function(err, $bundle) {
        var options;
        options = $bundle.get('options');
        if (err != null) {
          return _this._http500(err, $bundle.get('req'), $bundle.get('res'));
        } else {
          return _this._render({
            err: error.parse(err, $bundle.get('data')),
            req: $bundle.get('req'),
            res: $bundle.get('res'),
            template: "" + ($bundle.get('ctrl')) + "/" + ($bundle.get('func')),
            application: options.application
          });
        }
      };
      this._http404 = function(req, res, next) {
        return _this._render({
          err: error.parse('404'),
          req: req,
          res: res,
          template: "404"
        });
      };
      this._http500 = function(err, req, res, next) {
        return _this._render({
          err: error.parse(err),
          req: req,
          res: res,
          template: '500'
        });
      };
      this._bindRest();
    }

    Router.prototype._render = function(data) {
      var application, err, req, res, template, _ref;
      err = data.err, req = data.req, res = data.res, template = data.template, application = data.application;
      if (!application) {
        if (_ref = path.extname(req.url), __indexOf.call(_resTypes, _ref) >= 0) {
          application = path.extname(req.url);
        } else {
          application = this.application;
        }
      }
      switch (application) {
        case 'json':
          return res.status(err.toStatus()).json(err);
        default:
          return res.status(err.toStatus()).render(template, err.toData());
      }
    };

    Router.prototype._bindRest = function() {
      var _this = this;
      return ['get', 'post', 'put', 'delete'].map(function(method) {
        return _this[method] = function(route, options) {
          var to;
          if (options == null) {
            options = {};
          }
          to = options.to;
          if (to == null) {
            return logger.err("Missing Destination in Route: " + route);
          }
          return _this._applyCtrl([method, route, to], options);
        };
      });
    };

    Router.prototype._applyCtrl = function(rest, options) {
      var $ctrl, callback, ctrl, e, func, method, route, to, _ref;
      if (options == null) {
        options = {};
      }
      callback = options.callback || this.callback;
      method = rest[0], route = rest[1], to = rest[2];
      _ref = to.split('@'), ctrl = _ref[0], func = _ref[1];
      func = func || 'index';
      try {
        $ctrl = require("" + this.appRoot + "/controllers/" + ctrl);
        if (typeof ($ctrl != null ? $ctrl[func] : void 0) !== 'function') {
          return false;
        }
      } catch (_error) {
        e = _error;
        return logger.err("Missing Controller " + ctrl);
      }
      this._pushRest(rest);
      return this.app[method](route, function(req, res) {
        var $bundle;
        $bundle = bundle('rest');
        $bundle.set('req', req).set('res', res).set('func', func).set('ctrl', ctrl).set('options', options);
        return $ctrl[func].call($ctrl, $bundle, function(err, data) {
          $bundle.set('data', data);
          return callback(err, $bundle);
        });
      });
    };

    Router.prototype._pushRest = function(rest) {
      return this.rests.push(rest);
    };

    Router.prototype.showRests = function() {
      return this.rests;
    };

    Router.prototype.root = function(to, options) {
      if (options == null) {
        options = {};
      }
      return this._applyCtrl(['get', '/', to], options);
    };

    Router.prototype.resource = function(ctrl, options) {
      var rest, restMap, _i, _len, _results;
      if (options == null) {
        options = {};
      }
      restMap = [['get', "/" + ctrl, "" + ctrl + "@index"], ['get', "/" + ctrl + "/:id", "" + ctrl + "@show"], ['get', "/" + ctrl + "/:id/edit", "" + ctrl + "@edit"], ['get', "/" + ctrl + "/create", "" + ctrl + "@create"], ['post', "/" + ctrl, "" + ctrl + "@store"], ['put', "/" + ctrl + "/:id", "" + ctrl + "@update"], ['delete', "/" + ctrl + "/:id", "" + ctrl + "@destroy"]];
      _results = [];
      for (_i = 0, _len = restMap.length; _i < _len; _i++) {
        rest = restMap[_i];
        _results.push(this._applyCtrl(rest, options));
      }
      return _results;
    };

    Router.prototype.http404 = function(handle) {
      if (typeof handle === 'function') {
        this._http404 = handle;
      }
      this.app.use(this._http404);
      return this;
    };

    Router.prototype.http500 = function(handle) {
      if (typeof handle === 'function' && handle.length === 4) {
        this._http500 = handle;
      }
      this.app.use(this._http500);
      return this;
    };

    Router.prototype.alias = function() {};

    return Router;

  })();

  router = function(sundae) {
    var _router;
    _router = function(routes) {
      var $router;
      $router = new Router(sundae);
      if (typeof routes === 'function') {
        return routes.call($router);
      }
    };
    return _router;
  };

  router.Router = Router;

  module.exports = router;

}).call(this);
