// Generated by CoffeeScript 1.6.3
(function() {
  var Util, util;

  Util = (function() {
    function Util() {}

    return Util;

  })();

  util = new Util;

  module.exports = util;

}).call(this);
