// Generated by CoffeeScript 1.7.1
(function() {
  var assembler, async, backbone, config, ensure, filter, select, _;

  config = require('../config');

  async = require('async');

  _ = require('lodash');

  assembler = require('../middlewares/assembler');

  filter = require('../middlewares/filter');

  select = require('../middlewares/select');

  ensure = require('../middlewares/ensure');

  backbone = function($ctrl, ctrl, action, middlewares, req, res, callback) {
    return async.waterfall([
      function(next) {
        return async.eachSeries(middlewares, function(fn, _next) {
          return fn(req, res, _next);
        }, next);
      }, function(next) {
        return ensure($ctrl[action].ensure || $ctrl.ensure, req, next);
      }, function(next) {
        return filter($ctrl[action].filters || $ctrl.filters, req, next);
      }, function(next) {
        if ($ctrl[action].length === 3) {
          return $ctrl[action](req, res, next);
        } else {
          return $ctrl[action](req, next);
        }
      }, function(result, next) {
        if (typeof result === 'function') {
          next = result;
          result = {};
        }
        return assembler($ctrl[action].assemblers || $ctrl.assemblers, req, result, next);
      }, function(result, next) {
        if (typeof result === 'function') {
          next = result;
          result = {};
        }
        return select($ctrl[action].select || $ctrl.select, req, result, next);
      }
    ], function(err, result) {
      res.set('err', err);
      res.set('result', result);
      res.set('socketId', req.get('socketId'));
      if (err != null) {
        return callback(req, res);
      }
      if (typeof $ctrl[action].post === 'function') {
        $ctrl[action].post(req, res, result);
      }
      return callback(req, res);
    });
  };

  module.exports = backbone;

}).call(this);
