// Generated by CoffeeScript 1.7.1
(function() {
  var async, backbone;

  async = require('async');

  backbone = function($ctrl, ctrl, action, middlewares, req, res, callback) {
    return async.waterfall([
      function(next) {
        return async.eachSeries(middlewares, function(fn, _next) {
          return fn(req, res, _next);
        }, next);
      }, function(next) {
        if ($ctrl[action].length === 3) {
          return $ctrl[action](req, res, next);
        } else {
          return $ctrl[action](req, next);
        }
      }
    ], function(err, result) {
      res.set('err', err);
      res.set('result', result);
      if (err != null) {
        return callback(req, res);
      }
      if (typeof $ctrl[action].post === 'function') {
        $ctrl[action].post(req, res, result);
      }
      return callback(req, res);
    });
  };

  module.exports = backbone;

}).call(this);
