// Generated by CoffeeScript 1.7.1
(function() {
  var Err, ensure;

  Err = require('err1st');

  ensure = function(req, res, ensures, callback) {
    var missings;
    if (typeof ensures === 'string') {
      ensures = ensures.split(' ');
    }
    if (!(ensures instanceof Array)) {
      return callback(null);
    }
    missings = [];
    ensures.forEach(function(_ensure) {
      if (req.get(_ensure) == null) {
        return missings.push(_ensure);
      }
    });
    if (missings.length > 0) {
      return callback(new Err('MISSING_PARAMS', missings));
    }
    return callback(null);
  };

  ensure.before = true;

  ensure.key = 'ensure';

  ensure.parallel = false;

  module.exports = ensure;

}).call(this);
