// Generated by CoffeeScript 1.7.1
(function() {
  var Err, ensure;

  Err = require('err1st');

  ensure = function(req, res, callback) {
    var action, ctrl, _ref;
    return _ref = req.get(), ctrl = _ref.ctrl, action = _ref.action, _ref;
  };

  ensure.before = true;

  module.exports = ensure;

}).call(this);
