// Generated by CoffeeScript 1.7.1
(function() {
  var async, filter, _;

  async = require('async');

  _ = require('lodash');

  filter = function(req, res, list, callback) {
    if (toString.call(list) === '[object String]') {
      list = list.split(new RegExp(' +'));
    }
    if (toString.call(list) !== '[object Array]') {
      return callback(null);
    }
    return async.eachSeries(list, function(method, next) {
      return filter.filters[method](req, res, next);
    }, callback);
  };

  filter.filters = {};

  filter.before = true;

  filter.key = 'filters';

  filter.parallel = false;

  filter.initialize = function() {
    var e, sundae;
    sundae = require('../sundae');
    try {
      if (_.isEmpty(filter.filters)) {
        return filter.filters = require(sundae.get('mainPath'), 'middlewares', 'filters');
      }
    } catch (_error) {
      e = _error;
    }
  };

  module.exports = filter;

}).call(this);
