// Generated by CoffeeScript 1.6.3
(function() {
  var Router, router;

  Router = (function() {
    function Router() {
      this.mime = 'json';
    }

    Router.prototype.root = function() {};

    Router.prototype.resource = function(to, callback) {};

    Router.prototype.alias = function() {};

    return Router;

  })();

  router = new Router;

  router.Router = Router;

  module.exports = router;

}).call(this);
