// Generated by CoffeeScript 1.7.1
(function() {
  var select, _;

  _ = require('lodash');

  select = function(req, res, fields, result, callback) {
    var omits, picks, _select;
    if (callback == null) {
      callback = function() {};
    }
    if (toString.call(fields) === '[object String]') {
      fields = fields.split(new RegExp(' +'));
    }
    if (toString.call(fields) !== '[object Array]') {
      return callback(null, result);
    }
    picks = [];
    omits = [];
    fields.forEach(function(field) {
      if (field.indexOf('-') === 0) {
        return omits.push(field.slice(1));
      } else if (field.indexOf('+') === 0) {
        return picks.push(field.slice(1));
      } else {
        return picks.push(field);
      }
    });
    _select = function(result) {
      if (picks.length) {
        result = _.pick(result, picks);
      }
      if (omits.length) {
        result = _.omit(result, omits);
      }
      return result;
    };
    if (toString.call(result) === '[object Array]') {
      return callback(null, result.map(_select));
    } else if (toString.call(result) === '[object Object]') {
      return callback(null, _select(result));
    } else {
      return callback(null, result);
    }
  };

  select.after = true;

  select.key = 'select';

  select.parallel = false;

  module.exports = select;

}).call(this);
