// Generated by CoffeeScript 1.7.1
(function() {
  var Request;

  Request = require('../components/request');

  module.exports = function(app, fn) {
    var sundae;
    sundae = require('../sundae');
    return sundae.Request = (typeof fn === "function" ? fn(Request) : void 0) || Request;
  };

}).call(this);
