// Generated by CoffeeScript 1.7.1
(function() {
  var router;

  router = require('../components/router');

  module.exports = function(app, fn) {
    return typeof fn === "function" ? fn(router(app)) : void 0;
  };

}).call(this);
