// Generated by CoffeeScript 1.7.1
(function() {
  var async, before, util, _;

  async = require('async');

  _ = require('lodash');

  util = require('../util');

  before = function(list) {
    list = util._toArray(list);
    return function(req, res, callback) {
      var _ctrl;
      _ctrl = req._ctrl;
      return async.eachSeries(list, function(method, next) {
        var fn;
        fn = _ctrl[method];
        if (toString.call(fn) !== '[object Function]') {
          return next();
        }
        if (fn.length === 3) {
          return fn.call(_ctrl, req, res, next);
        } else {
          return fn.call(_ctrl, req, next);
        }
      }, callback);
    };
  };

  before.before = true;

  module.exports = before;

}).call(this);
