// Generated by CoffeeScript 1.7.1
(function() {
  var Err, e, ensure, util;

  try {
    Err = require('err1st');
  } catch (_error) {
    e = _error;
    Err = Error;
  }

  util = require('../util');

  ensure = function(ensures) {
    ensures = util._toArray(ensures);
    return function(req, res, callback) {
      var missings;
      if (callback == null) {
        callback = function() {};
      }
      missings = [];
      ensures.forEach(function(_ensure) {
        if (req.get(_ensure) == null) {
          return missings.push(_ensure);
        }
      });
      if (missings.length > 0) {
        return callback(new Err('MISSING_PARAMS', missings));
      }
      return callback(null);
    };
  };

  ensure.before = true;

  module.exports = ensure;

}).call(this);
