// Generated by CoffeeScript 1.7.1
(function() {
  var Err, e, ensure;

  try {
    Err = require('err1st');
  } catch (_error) {
    e = _error;
    Err = Error;
  }

  ensure = function(req, res, ensures, callback) {
    var missings;
    if (toString.call(ensures) === '[object String]') {
      ensures = ensures.split(new RegExp(' +'));
    }
    if (toString.call(ensures) !== '[object Array]') {
      return callback(null);
    }
    missings = [];
    ensures.forEach(function(_ensure) {
      if (req.get(_ensure) == null) {
        return missings.push(_ensure);
      }
    });
    if (missings.length > 0) {
      return callback(new Err('MISSING_PARAMS', missings));
    }
    return callback(null);
  };

  ensure.before = true;

  ensure.key = 'ensure';

  ensure.parallel = false;

  module.exports = ensure;

}).call(this);
