// Generated by CoffeeScript 1.7.1
(function() {
  var async, filter, _;

  async = require('async');

  _ = require('lodash');

  filter = function(req, res, list, callback) {
    var _ctrl;
    if (toString.call(list) === '[object String]') {
      list = list.split(new RegExp(' +'));
    }
    if (toString.call(list) !== '[object Array]') {
      return callback(null);
    }
    _ctrl = req._ctrl;
    return async.eachSeries(list, function(method, next) {
      var fn;
      fn = _ctrl[method];
      if (typeof fn !== 'function') {
        return next();
      }
      if (fn.length === 3) {
        return fn.call(_ctrl, req, res, next);
      } else {
        return fn.call(_ctrl, req, next);
      }
    }, callback);
  };

  filter.before = true;

  filter.key = 'filters';

  filter.parallel = false;

  module.exports = filter;

}).call(this);
