// Generated by CoffeeScript 1.7.1
(function() {
  var post;

  post = function(req, res, fn, result) {
    var _ctrl;
    if (result == null) {
      result = {};
    }
    if (typeof fn !== 'function') {
      return;
    }
    _ctrl = req._ctrl;
    return fn.call(_ctrl, req, res, result);
  };

  post.after = true;

  post.key = 'post';

  post.parallel = true;

  module.exports = post;

}).call(this);
