// Generated by CoffeeScript 1.7.1
(function() {
  var select, toJSON, util, _;

  _ = require('lodash');

  util = require('../util');

  toJSON = function(obj) {
    if (obj.toJSON) {
      return obj.toJSON();
    } else {
      return obj;
    }
  };

  select = function(fields) {
    fields = util._toArray(fields);
    return function(req, res, result, callback) {
      var omits, picks, _select;
      if (callback == null) {
        callback = function() {};
      }
      picks = [];
      omits = [];
      fields.forEach(function(field) {
        if (field.indexOf('-') === 0) {
          return omits.push(field.slice(1));
        } else if (field.indexOf('+') === 0) {
          return picks.push(field.slice(1));
        } else {
          return picks.push(field);
        }
      });
      _select = function(result) {
        result = toJSON(result);
        if (picks.length) {
          result = _.pick(result, picks);
        }
        if (omits.length) {
          result = _.omit(result, omits);
        }
        return result;
      };
      if (toString.call(result) === '[object Array]') {
        return callback(null, result.map(_select));
      } else if (toString.call(result) === '[object Object]') {
        return callback(null, _select(result));
      } else {
        return callback(null, result);
      }
    };
  };

  select.after = true;

  module.exports = select;

}).call(this);
